Bootstrap = window.Bootstrap || {};

// List of keywords that we use to bootstrap the system and get some URLs for testing
Bootstrap.Keywords = [
    // Top 1000 google keywords
    'facebook',
    'youtube',
    'google',
    'gmail',
    'hotmail',
    'xxnx',
    'xvideos',
    'amazon',
    'translator',
    'xxx',
    'pornos',
    'facebook login',
    'yahoo',
    'google translate',
    'yahoomail',
    'google maps',
    'ebay',
    'whatsapp',
    'porn',
    'instagram',
    'traductor',
    'weather',
    'redtube',
    'netflix',
    'outlook',
    'pokemon go',
    'twitter',
    'xhamster',
    'fahrenheit',
    'youporn',
    'olx',
    'craigslist',
    'msn',
    'grammes',
    'free porn',
    'beeg',
    'youtube mp3',
    'snapchat',
    'you',
    'messenger',
    'news',
    'sex',
    'videos pornotube',
    'ali express',
    'walmart',
    'bbc news',
    'google trad',
    'clash of clans',
    'linkedin',
    'tubidy',
    'pinterest',
    'vminecraft',
    'glob',
    'whatsapp web',
    'mincraft',
    'badoo',
    'bideo porno',
    'video porn',
    'ikea',
    'live score',
    'cnn',
    'cable news network',
    'e okul',
    'youtube to mp3',
    'olympics',
    'auol',
    'uolo',
    'speed test',
    'speedometer test',
    'minecraft',
    'traduttore',
    'game',
    'games',
    'paypal',
    'tiempos',
    'daily mail',
    'pornhub',
    'crikbuzz',
    'sahibinden',
    'MercadoLibre',
    'ok google',
    'libero mail',
    'milliyet',
    'bild',
    'marca',
    'marcar',
    'google tradutor',
    'euro 2016',
    'google onedrive',
    'ryanair',
    'traduttor',
    'myn',
    'skype',
    'aleg',
    'espn',
    'ebay kleinanzeigen',
    'factory automation',
    'football association',
    'mail',
    'mailen',
    'mails',
    'nynet',
    'beezars',
    'allegro',
    'convertidos',
    'sexuality video',
    'wp',
    'sex videos',
    'flipkart',
    'home depot',
    'home-depot',
    'hotel',
    'hotelaria',
    'restaurant',
    'restauration',
    'fox news',
    'iphone 7',
    'chaturbate',
    'ebay uk',
    'national basketball association',
    'nba',
    'g drive',
    'google drive',
    'bet365',
    'pokemom',
    'after service',
    'akciova spolecnost',
    'dropbox',
    'bed 365',
    'bookers',
    'booking',
    'zalando',
    'oranges',
    'calcu',
    'omegle',
    'indeed',
    'calculator',
    'calculators',
    'mp3',
    'pandora',
    'target',
    'zara',
    'airbnb',
    'best buy',
    'brazzers',
    'irctc',
    'cricbuzz',
    'uc browser',
    'phim sex',
    'gmx',
    'satta matka',
    'tubemate',
    'traductor google',
    'juegos',
    'hotels',
    'putlocker',
    'donald trump',
    'patriot ordnance factory',
    'pof',
    'restaurants',
    'bbc sports',
    'wells fargo',
    'pirate bay',
    'tumblr',
    'office 365',
    'office365',
    'youtube converter',
    'goggle docs',
    'billionaire boys club',
    'bbc',
    'wikipedia',
    'el mundo',
    'traduzir',
    'cam4',
    'leboncoin',
    'pizza hut',
    'pizzahut deals',
    'santander',
    'hentai',
    'el pais',
    'subway surfers',
    'brazzer',
    'brazzers',
    'roblox',
    'soundcloud',
    'bank of america',
    'google play',
    'gum tree',
    'spotify',
    'dominos',
    'interia',
    'goggle chrome',
    'staeam',
    'steam',
    'international mathematics olympiad',
    'playstore',
    'apple',
    'groupon',
    'itube.com',
    'amazon uk',
    'amazon united kingdom',
    'cricinfo',
    'argos',
    'atgis',
    'augos',
    'tube8',
    'xxx video',
    'facebook lite',
    'adna klasnik',
    'odnoklassniki',
    'imdb',
    'aol mail',
    'aol mailbox',
    'sports',
    'man united',
    'justin bieber',
    'state bank india online',
    'american online inc',
    'sbi online',
    'google docs',
    'backpages',
    'lowes',
    'cosco',
    'aol',
    'bing',
    'wwe',
    'anti virus',
    'dich',
    'hdfc netbanking',
    'auto trader',
    'candy crush',
    'perfect girl',
    'expedia',
    'vodafone',
    'adidas',
    'porn tube',
    'pornstar tube',
    'kooora',
    'trivago',
    'liber',
    'nike',
    'viber',
    'google chrome',
    'chrome',
    'chromed',
    'trip advisor',
    'automated surface observing system',
    'whatsapp messenger',
    'line',
    'macys',
    'skyscanner',
    'facebook en espa ol',
    'decathlon',
    'shareit',
    'snap deal',
    'snapdeal',
    '24h',
    'internet movie database',
    'banco de venezuela',
    'reddit',
    'icloud',
    'uber',
    'trump',
    'game of thrones',
    'aright move',
    'peppa pig',
    'deadpool',
    'national football league',
    'nfl',
    'samsung',
    'world star hip hop',
    'aloewishes',
    'anime goog',
    'mp3xd',
    'lotto',
    'meenakshisundaram',
    'metros',
    'monsieur',
    'alvyda',
    'american airlines',
    'ansaa',
    'flashscore',
    'real madrid',
    'itunes',
    'accuweather',
    'yandex',
    'youtube downloader',
    'capital one',
    'dailymotion',
    'hsbc',
    'email',
    'pages jaunes',
    'google earth',
    'mcdonalds',
    'asck',
    'clean master',
    'amazon prime',
    'ask',
    'imo',
    'porno gratis',
    'pornogratis',
    'usps tracking',
    'zillows',
    'kohls',
    'paytm',
    'gta',
    'costco',
    'facebook messenger',
    'happy wheels',
    'kim kardashian',
    'porn video',
    'toys r us',
    'cricket scoreboard',
    'cricket scores',
    'traducir',
    'mercado libre',
    'mexican restaurants near me',
    'nfl scores',
    'dravi',
    'star wars',
    'google scholar',
    'cooi math gams',
    'cool math game',
    'solitaire',
    'afton bladet',
    'google news',
    'google images',
    'tinder',
    'chase',
    'goggle images',
    'caf',
    'iltalehti',
    'vpn',
    'goggle news',
    'iphone 6s',
    'selena gomez',
    'mp3 converter',
    'aresanel',
    'driver',
    'suicide squad',
    'mobile',
    'mobili',
    'wallpapers',
    'wc',
    'forever 21',
    'powerball',
    'ticketmaster',
    'web whatsapp',
    'a erocam aor omes',
    'asrnel',
    'bbc weather',
    'hotmaillogin',
    'corrosion of conformity',
    'windows 10',
    'easyjet',
    'hot',
    'litre',
    'mapquest',
    'vn express',
    'kizi',
    'youtube videos',
    'bradesco',
    'lol',
    'clarin',
    'photo edit',
    'photography editing',
    'trenitalia',
    'candy crush saga',
    'fanatik',
    'mappy',
    'b6 12',
    'meteos',
    'celsius',
    'firefox',
    'grand theft auto',
    'greater toronto area',
    'kik',
    'next',
    'victoria secret',
    'sexo',
    'teamviewer',
    'etsy',
    'bla bla car',
    'indian railway',
    'lazada',
    'pnr-status',
    'hotstar',
    'x video',
    'bidmate',
    'jogos',
    'mfacebook',
    'la caixa',
    't-mobile',
    'hillary clinton',
    'restaurant near me',
    'ymz',
    'tmz',
    'Ariana Grande',
    'sky news',
    'mp3 juice',
    'ig',
    'cool math',
    'the walking dead',
    'ilta-sanomat',
    'arsenal',
    'asana',
    'barca',
    'barcelona',
    'barcelonistas',
    'sky sports',
    'ultimate fighting championship',
    'taylor swift',
    'banisteriopsis',
    'general motors',
    'genetically modified',
    'gm',
    'le monde',
    'web',
    'kurir',
    'chased',
    'prince',
    '123movies',
    'kayak',
    'b lic',
    'minion',
    'music downloader',
    'youtube music',
    'edmodo',
    'cars',
    'hola',
    'att',
    'happy birthday',
    'dee',
    'iphone 6',
    'wish',
    'papa johns',
    'sat',
    'major league baseball',
    'mlb',
    'australian broadcasting corporation',
    'index',
    'indexer',
    'credit karma',
    'snap tube',
    'aloha tube',
    'banco estado',
    'kickass',
    'aphotoshop',
    'abc',
    'fifa 16',
    'db',
    'deutsche bahn',
    'iphone 5s',
    'actualitees',
    'messi',
    'kylie jenner',
    'utorrent',
    'image',
    'terra',
    'google classrooms',
    'rediffmail',
    'torrents',
    'extra torrent',
    'xdj',
    'starbucks',
    'movies',
    'matka',
    'wordreference',
    'anime',
    'sarkari result',
    'retrica',
    '4shared',
    'kahoot',
    'habe',
    'ups track',
    '9 gag',
    'antozone',
    'auroson',
    'auroxone',
    'gazeteler',
    'tesco',
    'bank2u',
    'downloads',
    'mango',
    'ok',
    'qvc',
    'unicredit',
    'banco bilbao vizcaya argentaria',
    'bbvas',
    'horoscope',
    '24 sata',
    'baqnesco',
    'credit agricole',
    'bed bath and beyond',
    'buienradar',
    'old navy',
    'arefour',
    'dictionaries',
    'dictionary',
    'foot locker',
    'footlocker',
    'j.c. penney',
    'pnr status',
    'amerikano',
    'aricanas',
    'gamestop',
    'nordstrom',
    'bookmyshow',
    'liverpool',
    'rambler',
    'major league baseball scores',
    'mlb scores',
    'nba scores',
    'the pirate bay',
    'golden state warriors',
    'onedrive',
    'cheap flights',
    'vertalen',
    'cheapest flights',
    'citi bank',
    'outlook 365',
    'chase online',
    'watch series',
    'david bowie',
    'google flights',
    'bbc football',
    'united airlines',
    'bernie sanders',
    'testing',
    'tests',
    'toyota',
    'webmail',
    'ajva',
    'fitbit',
    'java',
    'american express',
    'gay porn',
    'ivanovic',
    'television guide',
    'tv guide',
    'cristiano ronaldo',
    'rihanna',
    'southwest airlines',
    'sw airlines',
    'java -djava.security.policy',
    'oppure',
    'ovvero',
    'spider man',
    'online sbi',
    'bmw',
    'music',
    'ynet',
    'dragon ball super',
    'iphones',
    'anerucab exoress',
    'verizon',
    'icicinet banking',
    'roku',
    'popcorn time',
    'pornhd',
    'delfi',
    'sabah',
    'hello',
    'eme',
    'winrar',
    'youtubes music',
    'n',
    'united states post office',
    'east',
    'premier league',
    'piano',
    'skies',
    'sky',
    'mp3 downloader',
    'asda',
    'geometry dash',
    'foot',
    'football',
    'flashlight',
    'mobile de',
    'tubegalore',
    'photoshop',
    'ps4',
    '360 security',
    'thesaurus',
    'ups',
    'free sex',
    'uninterrupted power supply',
    'adobe reader',
    'subway',
    'league of legends',
    'movistar',
    'guardian',
    'guardians',
    'fedex',
    'gmail login',
    'applock',
    'naruto',
    'apps',
    'grand theft auto 5',
    'o2',
    'anemei',
    'currency converter',
    'emoji',
    'walgreen',
    'john lewis',
    'milf',
    'wechat',
    'hd porn',
    'download',
    'moto gp',
    'sears',
    'autozone',
    'bideos porno gratis',
    'huffington post',
    'porn hd',
    'telecinco',
    'chatro',
    'chatroulet',
    'la repubblica',
    'photo grid',
    'animal jam',
    'apple store',
    'avitop',
    'palmeiras',
    'aldis',
    'candy camera',
    'christian outreach centre',
    'segunda mano',
    'videos porno gratis',
    'bonprix',
    'carrefour',
    'cinemark',
    'new look',
    'times of india',
    'truecaller',
    'antera vasna',
    'fnac',
    'live cricket score',
    'live cricket scoreboard',
    'program tv',
    'netbanking',
    'conor mcgregor',
    'comcast',
    'mail online',
    'halifax',
    'adobe flash player',
    'coco',
    'teen porn',
    'pubmed',
    'honda',
    'lottery',
    'plenty of fish',
    'a bola',
    'bee bee',
    'expressing',
    'expression',
    'lloyds',
    'amel',
    'amelie',
    'adele',
    'frozen',
    'people',
    'video one',
    'hyundai',
    'spiegel',
    'captain america civil war',
    'kendall jenner',
    'national hockey league',
    'federation internationale de football association',
    'fifa',
    'natwest',
    'beyonce',
    'dragon city',
    'drudge report',
    'iphone se',
    'nudevista',
    'fandango',
    'google-analytics',
    'bod',
    'harry potter',
    'champions league',
    'us bank',
    'microsoft',
    'mundo deportivo',
    'fc barcelona',
    'hay day',
    'chelsea',
    'le figaro',
    'mp3 music downloading',
    'xbox one',
    'ford',
    'volkswagen',
    'angelina jolie',
    'leos',
    'el confidencial',
    'michael kors',
    'translate google',
    'british airways',
    'eurosport',
    'afipo',
    'la nacion',
    'mega',
    'warrior',
    'jota',
    'record',
    'b anco do brasil',
    'fallout 4',
    'nicki minaj',
    'pac-man',
    'mercedes',
    'rojadirecta',
    'slither',
    'societe generale',
    'avob',
    'avon',
    'mia khalifa',
    'one piece',
    'fifa 15',
    'booking.com',
    'jav',
    'anco santander',
    'chromecast',
    'lego',
    'cartolas',
    'telegram',
    'radio',
    'sex tube',
    'myfreecams',
    'shazam',
    'sudoku',
    'asds',
    'jeux',
    'urban dictionary',
    'deezer',
    'marks and spencer',
    'air france',
    'cars game',
    'staple',
    'video downloader',
    'acura games',
    'camera 360',
    'car g',
    'car game',
    'la poste',
    'vlc',
    'abast',
    'airasia',
    'mahjong',
    'paris',
    'pdf',
    'porno xxx',
    'pornografia xxx',
    'pornos xxx',
    'portable document format',
    'temple run 2',
    'avast',
    'avsst',
    'dainikbhaskar',
    'fedex track',
    'fedex tracking',
    'porn movies',
    'porno movies',
    'whatsapp download',
    '9apps',
    'k mart',
    'launcher',
    'otto',
    'laredoute',
    'serie a',
    'conforama',
    'debenhams',
    'kmart',
    'white pages',
    'whitepages',
    'meetic',
    'cinepolis',
    'lojas americanas',
    'redbox',
    'bershka',
    'garanti',
    'mx player',
    'tokopedia',
    'zalo',
    'viamichelin',
    'correios',
    'tredyol',
    'cargams',
    'traductor de google',
    'yahoo finance',
    'johnny depp',
    'leonardo dicaprio',
    'ok cupid',
    'buzzfeed',
    'bancoombia',
    'pizza',
    'george boole',
    'corriere',
    'expressen',
    'anime flv',
    'aprint',
    'earth day',
    'periscope',
    'spanish to english',
    'xfinity',
    'rezultati',
    'asprint',
    'william hill',
    'william shakespeare',
    'nordea',
    'sprint',
    'scholar',
    'scholarship',
    'barclay',
    'barclays',
    'ask.fm',
    'national lottery',
    'tiscali',
    'cub',
    'el comercio',
    'isis',
    'samsung galaxy s7',
    'audi',
    'blogger',
    'el universal',
    'the revenant',
    'quot',
    'quotes',
    'rio 2016',
    'google analytics',
    'halloween',
    'miniclip',
    'western union',
    'katy perry',
    'one direction',
    'a naked girl',
    'boo hoo',
    'focus',
    'neymar',
    'banco provincial',
    'yelp',
    'delta',
    'drake',
    'film streaming',
    'nissan',
    'batman',
    'hoverboard',
    'quizlet',
    'snap',
    'yahoo news',
    'british telecom',
    'brad pitt',
    'copa america',
    'juventus',
    'sonic',
    'bekmen',
    'tesla',
    'avianca',
    'google calendar',
    'verizon wireless',
    'sex stories',
    'hangout',
    'jworg',
    'barbie',
    'bundesliga',
    'chatting',
    'moneycontrol',
    'television online',
    'meme',
    'photo',
    'free games',
    'free gaming',
    'freeware games',
    'need for speed',
    'cricket',
    'harley quinn',
    'provincial',
    'michael jackson',
    'tango',
    'vivo',
    'goggle mail',
    'cartoon network',
    'paris saint-germain',
    'burger king',
    'camera',
    'comuniazo',
    'primark',
    'angry birds',
    'alibaba',
    'boot',
    'global positioning system',
    'office depot',
    'batman vs superman',
    'dragon ball z',
    'party city',
    'banki',
    'adblock',
    'euro',
    'imgur',
    'akinator',
    'curries',
    'curry',
    'flash player',
    'google mail',
    'opera',
    'piano tiles',
    'planetromeo',
    'banco do brasil',
    'kfc',
    'bancosantander chile',
    'keyboard',
    'pacman',
    '8ball pool',
    'bnp',
    'british national party',
    'el corte ingles',
    'f1',
    'zedge',
    'app lock',
    'applications lock',
    'free porn videos',
    'jennifer lawrence',
    'literot',
    'literotica',
    'louis vuitton',
    'river island',
    'sex xxx',
    'what',
    'bluestacks',
    'galinha pintadinha',
    'gossip',
    'margot robbie',
    'miley cyrus',
    'barnes and noble',
    'gitt',
    'make my trip',
    'michael',
    'pegasus',
    'plants vs zombies',
    'hobby lobby',
    'waze',
    'canadian tire',
    'e-mag',
    'american eagle',
    'gta san andreas',
    'dubsmash',
    'falabella',
    'gazeta',
    'stradivarius',
    'uc mini',
    'urban outfitters',
    'zing',
    'extras',
    'casto',
    'rotten tomatoes',
    'stephen curry',
    'club penguin',
    'mlb standings',
    'cat',
    'kanye west',
    'cici',
    'scratch',
    'zeta',
    'national rail',
    'train running status',
    'vikings',
    'time',
    'free mobile',
    'adobe',
    'naked girl',
    'fabswingers',
    'flickr',
    'transformers',
    'english soccer premier league',
    'mac',
    'kickers',
    'shemale',
    'enterprise',
    'songs',
    'emoji keyboard',
    'tetris',
    'mario',
    'live television',
    'lufthansa',
    'vivastreet',
    'gaps',
    'mobo market',
    'dick sporting goods',
    'nude',
    'sexy',
    'trade me',
    'scotiabank',
    'livecricket',
    'shopclues',
    'american eagle',
    'submarino',
    'elmundo',
    'chatroulette',
    'flower',

    // Top 100 internation google searches
    'when was the first cricket test match', 
    'minna canth', 
    'komodo dragon preserve', 
    'holi frühlingsfest 2017', 
    'セルゲイ ディアギレフ', 
    'ハッサン・ファトヒー', 
    'dünya kadınlar günü 2017', 
    'cyclone debbie', 
    'marcel heße', 
    'when was the first cricket test match', 
    'where is komodo national park?', 
    'suchi leaks', 
    'hari perempuan internasional 2017', 
    'nyse:snap', 
    'ngày quốc tế phụ nữ 2017', 
    'lente-equinox', 
    'けものフレンズ 11話', 
    'ตรวจหวย16มีนาคม2560', 
    'モンハンダブルクロス 攻略', 
    'ygs sonuçları 2017', 
    'samurai jack season 5 episode 3', 
    'niebieski wieloryb gra', 
    'are komodo dragons endangered?', 
    'holi frühlingsfest 2017', 
    'dove si trova il parco nazionale di komodo?', 
    'けものフレンズ 12話', 
    '하싼 화티', 
    '121g site:oreillyauto.com', 
    'holi frühlingsfest 2017', 
    'how fast can komodo dragons run?', 
    'holi, fête des couleurs', 
    'コモド国立公園の場所', 
    'niebieski wieloryb zadania', 
    'cyclone debbie update', 
    'bangladesh independence day 2017', 
    'serge de diaghilev', 
    'mhxx キークエ', 
    'vaio phone a', 
    'sergei diaghilev', 
    'st.patrick\'s day 2017', 
    'operação carne fraca', 
    'westminster attack', 
    'google play fish farm 2', 
    'アトラル・カ', 
    'モンハンダブルクロス キークエ', 
    'わんずまざー保育園', 
    '¿dónde está el parque nacional de komodo?', 
    'ไดอารี่ตุ้ดซี่ 2 ep4', 
    'how heavy are komodo dragons?', 
    'malina klaar', 
    '¿dónde está el parque nacional de komodo?', 
    'pb ampera', 
    '八田尚輝', 
    '性の喜びおじさん 死亡', 
    'primeiro dia primavera 2017', 
    'между нами тает лед', 
    'bs 3 vehicles', 
    'suchi leaks videos', 
    'suchitra leaks', 
    'かごいけ', 
    'ゼルダの伝説 ブレス オブ ザ ワイルド 攻略', 
    'грибы тает лед', 
    'sviatok holí', 
    'ไดอารี่ตุ้ดซี่ 2 ep5', 
    'สอบครูผู้ช่วย 60', 
    'brad\'s wife', 
    'journée internationale des droits des femmes 2017', 
    'hassan fathy', 
    'draghi di komodo rischio estinzione', 
    'хасан фати', 
    'ปัจจัยพื้นฐานนักเรียนยากจน', 
    '科莫多國家公園', 
    'keo ruug shrine', 
    'moomoo.io', 
    'ホライゾンゼロドーン 攻略', 
    '辻元清美 生コン', 
    'зкд 2 сезон 5 серия', 
    'cookie too big', 
    'prince sidon', 
    'suchi leaks', 
    'lokasi taman nasional komodo?', 
    'journée internationale des droits des femmes 2017', 
    'stemwijzer 2017 nl', 
    'ตรวจหวย16/03/60', 
    'ไดอารี่ตุ้ดซี่ 2 ep6', 
    'skip challenge', 
    'コモドオオトカゲ 保全状況', 
    'suchileaks', 
    'モンスト ブリザーガ', 
    'suchi leaks twitter', 
    'journée internationale des droits des femmes 2017', 
    'митинг 26 марта', 
    'เสียภาษีปี 2560', 
    'lorde green light', 
    'nyse:snap', 
    'ตรวจสลากกินแบ่งรัฐบาล 16 มีนาคม 2560', 
    'payut ngaokrachang', 
    '¿dónde está el parque nacional de komodo?', 
    'sergei diaghilev', 

    // From a list of Chinese nouns
    '状态', 
    '地段', 
    '女人', 
    '国内', 
    '生活', 
    '问题', 
    '总统', 
    '孩子', 
    '一周', 
    '世界', 
    '那种', 
    '案件', 
    '问题', 
    '事实', 
    '家庭', 
    '这个故事', 
    '点', 
    '政府', 
    '钱', 
    '问题', 
    '部分', 
    '清晨', 
    '那家伙', 
    '数量', 
    '就业', 
    '夜晚', 
    '正确的', 
    '学校', 
    '的地方', 
    '战争', 
    '孩子', 
    '一个月', 
    '本书', 
    '小时', 
    '演出', 
    '警方', 
    '该程序', 
    '党', 
    '法律', 
    '字', 
    '此人', 
    '主场', 
    '业务', 
    '朋友', 
    '公司', 
    '侧面', 
    '税', 
    '民主党', 
    '该集团', 
    '瞬间', 
    '破', 
    '这个想法', 
    '成员', 
    '系统', 
    '一分钟', 
    '原因', 
    '竞选', 
    '工作', 
    '全国', 
    '大会', 
    '母亲', 
    '力', 
    '健康', 
    '背部', 
    '区域', 
    '名字', 
    '报告', 
    '手', 
    '行', 
    '结束', 
    '法院', 
    '护理', 
    '夫妻', 
    '房子', 
    '美国', 
    '父亲', 
    '情况', 
    '汽车', 
    '父', 
    '管理', 
    '药物', 
    '城市', 
    '感', 
    '政策', 
    '办公室', 
    '决定', 
    '动力', 
    '计划', 
    '领导者', 
    '信息', 
    '选', 
    '电影', 
    '死亡', 
    '空气', 
    '通话', 
    '社区', 
    '外观', 
    '证据', 
    '女孩', 
    '医生', 
    '投票', 
    '视频', 
    '图片', 
    '房间', 
    '该位', 
    '经济', 
    '手机', 
    '历史', 
    '排序', 
    '男孩', 
    '犯罪', 
    '流程', 
    '妻子', 
    '音乐', 
    '水', 
    '服务', 
    '记录', 
    '安全', 
    '会谈', 
    '心灵', 
    '头部', 
    '候选', 
    '官方', 
    '摄像头', 
    '学生', 
    '攻击', 
    '机会', 
    '游戏', 
    '宝宝', 
    '南方', 
    '变化', 
    '试用', 
    '身体', 
    '市场', 
    '东东', 
    '兴趣', 
    '武器', 
    '的心脏', 
    '儿子', 
    '球队', 
    '小镇', 
    '电视', 
    '意志', 
    '队伍', 
    '法官', 
    '行动', 
    '答案', 
    '位置', 
    '视图', 
    '区别', 
    '食品', 
    '女儿', 
    '比赛', 
    '成交', 
    '街头', 
    '价格', 
    '消息', 
    '控制', 
    '辩论', 
    '军官', 
    '电影', 
    '水平', 
    '努力', 
    '关系', 
    '记者', 
    '地面', 
    '片', 
    '丈夫', 
    '预算', 
    '陪审团', 
    '记者', 
    '周末', 
    '此事', 
    '年龄', 
    '枪', 
    '和平', 
    '谋杀', 
    '角色', 
    '调查', 
    '经验', 
    '医院', 
    '眼', 
    '导演', 
    '未来', 
    '面对', 
    '油', 
    '结果', 
    '公众', 
    '律师', 
    '民意调查', 
    '第二', 
    '机会', 
    '行业', 
    '的哥', 
    '声明', 
    '火', 
    '爱情', 
    '率', 
    '效果', 
    '这首歌', 
    '事件', 
    '充电', 
    '支持', 
    '无线电', 
    '建筑', 
    '银行', 
    '受害者', 
    '门', 
    '采访', 
    '现场', 
    '其余的部分', 
    '新闻', 
    '注意', 
    '选择', 
    '讲话', 
    '病人', 
    '真相', 
    '在路上', 
    '期限', 
    '网站', 
    '工人', 
    '教授', 
    '信', 
    '改革', 
    '关注', 
    '民间', 
    '性别', 
    '研究', 
    '学院', 
    '选民', 
    '墙上', 
    '晚上', 
    '会议', 
    '声音', 
    '观众', 
    '暴力', 
    '规则', 
    '明星', 
    '测试', 
    '教育', 
    '麻烦', 
    '风险', 
    '监狱', 
    '客人', 
    '类', 
    '社会', 
    '士兵', 
    '飞机', 
    '量', 
    '帮助', 
    '成本', 
    '权威', 
    '脚', 
    '期', 
    '感觉', 
    '步骤', 
    '事业', 
    '磁带', 
    '威胁', 
    '意见', 
    '该组织', 
    '类型', 
    '谈话', 
    '本病', 
    '操作', 
    '癌症', 
    '该杂志', 
    '州长', 
    '压力', 
    '多数', 
    '研究', 
    '字符', 
    '该站', 
    '危机', 
    '专家', 
    '血', 
    '董事长', 
    '参数', 
    '名单', 

    // From a list of Bulgarian words
    'това',
    'онова',
    'тук',
    'там',
    'кой',
    'какъв',
    'къде',
    'кога',
    'как',
    'не',
    'всички; цял/целият',
    'много',
    'няколко',
    'малко',
    'друг',
    'един',
    'две',
    'три',
    'четири',
    'пет',
    'голям',
    'дълъг',
    'широк',
    'плътен, дебел',
    'тежък',
    'малък, дребен',
    'къс, кратък',
    'тесен',
    'слаб, тънък',
    'жена',
    'мъж',
    'човек',
    'дете',
    'съпруга',
    'съпруг',
    'майка',
    'баща, татко',
    'животно',
    'риба',
    'птица',
    'куче, пес, псе',
    'въшка',
    'змия',
    'червей',
    'дърво',
    'гора, лес',
    'пръчка, съчка, клонче, клечка, стрък(че)',
    'плод',
    'семе',
    'листо, лист',
    'корен',
    'кора',
    'цвете',
    'трева',
    'въже',
    'кожа',
    'месо',
    'кръв',
    'кокал, кост',
    'мазнина, тлъстина, лой',
    'яйце',
    'рог',
    'опашка',
    'перо',
    'коса, косъм',
    'глава',
    'ухо',
    'око',
    'нос',
    'уста',
    'зъб',
    'език',
    'нокът',
    'крак, стъпало, ходило, нога',
    'крак',
    'коляно',
    'ръка',
    'крило',
    'корем, търбух',
    'вътрешности, черва',
    'врат, шия',
    'гръб, гърбина',
    'гръд, гърда',
    'сърце',
    'черен дроб',
    'пия',
    'ям',
    'хапя',
    'суча',
    'плюя',
    'повръщам, бълвам',
    'духам',
    'дишам',
    'смея се',
    'виждам',
    'чувам, слушам',
    'зная',
    'мисля',
    'мириша, душа',
    'страхувам се, боя се, опасявам се',
    'спя',
    'живея',
    'умирам',
    'убивам',
    'бия се',
    'ловувам',
    'удрям',
    'режа, сека',
    'цепя',
    'промушвам, пробождам, наръгвам',
    'драскам, дращя; чеша',
    'копая, ровя',
    'плувам',
    'летя',
    'вървя, ходя',
    'идвам, пристигам, дохождам',
    'лежа',
    'седя',
    'стоя',
    'завивам',
    'падам',
    'давам',
    'държа',
    'изцеждам, изстисквам',
    'трия, търкам',
    'мия',
    'бърша, трия, търкам',
    'дърпам, тегля, влача',
    'бутам, блъскам, тикам, тласкам',
    'хвърлям, мятам',
    'връзвам, завързвам',
    'шия',
    'броя, смятам, изчислявам',
    'казвам',
    'пея',
    'играя',
    'плавам',
    'тека',
    'замръзвам, замразявам (се), заледявам (се)',
    'подувам се, отичам',
    'слънце',
    'луна, месечина, месец',
    'звезда',
    'вода',
    'дъжд',
    'река',
    'езеро',
    'море',
    'сол',
    'камък',
    'пясък',
    'прах',
    'земя, суша',
    'облак',
    'мъгла',
    'небе',
    'вятър',
    'сняг',
    'лед',
    'пушек, дим',
    'огън',
    'пепел',
    'горя',
    'път',
    'планина',
    'червен',
    'зелен',
    'жълт',
    'бял',
    'черен',
    'нощ',
    'ден',
    'година',
    'топъл',
    'студен, хладен',
    'пълен, цял',
    'нов',
    'стар',
    'добър',
    'лош',
    'гнил',
    'мръсен, нечист',
    'прав, пряк',
    'кръгъл',
    'остър',
    'тъп',
    'гладък',
    'мокър, влажен',
    'сух',
    'правилен, верен, точен',
    'близък',
    'далечен',
    'десен'
];